modules/cpanel/controllers/AgentController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\Agent;
use app\models\AgentContact;
use app\models\search\AgentSearch;
use app\modules\cpanel\components\CpanelController;
use app\modules\cpanel\models\Model;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\web\Response;

class AgentController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = Agent::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        $modelsContact =[];

        if($new === true){
            $model = $this->createModel($this->modelName);
            $modelsContact = [new AgentContact()];
            $model->is_customer = 1;
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
            foreach ($model->contacts as $contact){
                $modelsContact[] = $contact;
            }
            if(!$modelsContact) $modelsContact = [new AgentContact()];
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $modelsContact = Model::createMultiple(AgentContact::classname());

            Model::loadMultiple($modelsContact, \Yii::$app->request->post());

             if ($model->save()) {
                 $model->deleteContacts();
                 foreach ($modelsContact as $item) {
                     $item->link('agent', $model);
                     $item->save(false);
                 }
                 $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            if(!\Yii::$app->request->isAjax) {
                return $this->redirect('list');
            } else {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return ['id' => $model->id];
            }
        }

        if(\Yii::$app->request->isAjax)
            if($model->errors) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $result = array('error' => 'true');
                return array_merge($result, ActiveForm::validate($model));
            } else
                return $this->renderAjax('form', ['model' => $model, 'modelsContact' => $modelsContact, 'callback' => \Yii::$app->request->get('callback')]);

    }

    public function actionValidate()
    {
        $model = $this->createModel($this->modelName);

        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

    }

    public function actionDetails(){
        if(\Yii::$app->request->isAjax) {
            $post = \Yii::$app->request->post();
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $agent = Agent::findOne($post['agent_id']);
            return ['agent' => $agent, 'contacts' => ($agent ? $agent->contacts : null)];
        }
    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Item deleted successfully !'));
        else
            $this->setFlash('error', \Yii::t('app', 'Item has not been deleted !'));

        return $this->redirect(['list']);

    }

    public function actionList(){

        $search = new Agent();
        $provider = $search->search(\Yii::$app->request->get());


        return $this->render('list', ['provider' => $provider, 'searchModel' => $search]);

    }

}

modules/cpanel/controllers/CompanyController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\Company;
use app\modules\cpanel\components\CpanelController;

class CompanyController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = Company::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        if($new === true){
            $model = $this->createModel($this->modelName);
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

             if ($model->save()) {
                $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            return $this->redirect('list');
        }


        return $this->render('form', ['model' => $model]);

    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect(['list']);

    }

    public function actionList(){

        $model = $this->createModel($this->modelName);

        return $this->render('list', ['provider' => $model->getProvider()]);

    }

}

modules/cpanel/controllers/StatusController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\Status;
use app\modules\cpanel\components\CpanelController;

class StatusController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = Status::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        if($new === true){
            $model = $this->createModel($this->modelName);
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

             if ($model->save()) {
                $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            return $this->redirect('list');
        }


        return $this->render('form', ['model' => $model]);

    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect(['list']);

    }

    public function actionList(){

        $model = $this->createModel($this->modelName);

        return $this->render('list', ['provider' => $model->getProvider()]);

    }

}

modules/cpanel/controllers/UserController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\User;
use app\modules\cpanel\components\CpanelController;

class UserController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = User::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        if($new === true){
            $model = $this->createModel($this->modelName);
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

             if ($model->save()) {
                $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            return $this->redirect('list');
        }


        return $this->render('form', ['model' => $model]);

    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect(['list']);

    }

    public function actionList(){

        $model = $this->createModel($this->modelName);

        return $this->render('list', ['provider' => $model->getProvider()]);

    }

}

modules/cpanel/views/layouts/footer.php
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">SmartAdmin 1.8.2 <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <!--<i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i> -->
                <div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

modules/cpanel/views/layouts/header.php
<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <a href="/"><img src="/img/logo_old.png" height="52px" alt="SmartAdmin"></a> </span>
        <!-- END LOGO PLACEHOLDER -->

        <!-- Note: The activity badge color changes when clicked and resets the number to 0
             Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
        <!--<span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge bg-color-red bounceIn animated"> 21 </b> </span>
        -->
        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
        <!--
        <div class="ajax-dropdown">

            <div class="btn-group btn-group-justified" data-toggle="buttons">
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="ajax/notify/mail.html">
                    Msgs (14) </label>
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="ajax/notify/notifications.html">
                    notify (3) </label>
                <label class="btn btn-default">
                    <input type="radio" name="activity" id="ajax/notify/tasks.html">
                    Tasks (4) </label>
            </div>


            <div class="ajax-notifications custom-scroll">

                <div class="alert alert-transparent">
                    <h4>Click a button to show messages here</h4>
                    This blank page message helps protect your privacy, or you can show the first message here automatically.
                </div>

                <i class="fa fa-lock fa-4x fa-border"></i>

            </div>

					<span> Last updated on: 12/12/2013 9:43AM
						<button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
							<i class="fa fa-refresh"></i>
						</button> </span>


        </div>


    </div>


    <div class="project-context hidden-xs">


        <ul class="dropdown-menu">
            <li>
                <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
            </li>
            <li>
                <a href="javascript:void(0);">Notes on pipeline upgradee</a>
            </li>
            <li>
                <a href="javascript:void(0);">Assesment Report for merchant account</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
            </li>
        </ul>

-->
    </div>


    <!-- #TOGGLE LAYOUT BUTTONS -->
    <!-- pulled right: nav area -->
    <div class="pull-right">

        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
            <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>
        <!-- end collapse menu -->

        <!-- #MOBILE -->
        <!-- Top menu profile link : this shows only when top menu is active -->
        <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
            <li class="">
                <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                    <img src="/img/avatars/sunny.png" alt="John Doe" class="online">
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
                    </li>
                </ul>
            </li>
        </ul>

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
            <span>
                <?= \yii\helpers\Html::a(
                      '<i class="fa fa-sign-out"></i>',
                    ['/cpanel/default/logout'],
                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat',
                    'data-logout-msg' => Yii::t('app', 'Sign out'),
                    'title' => Yii::t('app', 'Sign out'),
                    //'data-action' => 'userLogout'
                    ]
                ) ?>
                <!--<a href="login.h" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> -->
            </span>
        </div>
        <!-- end logout button -->

        <!-- search mobile button (this is hidden till mobile view port)
        <div id="search-mobile" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
        </div>-->
        <!-- end search mobile button -->

        <!-- #SEARCH -->
        <!-- input: search field
        <form action="search.html" class="header-search pull-right">
            <input id="search-fld" type="text" name="param" placeholder="Find reports and more">
            <button type="submit">
                <i class="fa fa-search"></i>
            </button>
            <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
        </form>-->
        <!-- end input: search field -->

        <!-- fullscreen button -->
        <div id="fullscreen" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
        </div>
        <!-- end fullscreen button -->

        <!-- #Voice Command: Start Speech
        <div id="speech-btn" class="btn-header transparent pull-right hidden-sm hidden-xs">
            <div>
                <a href="javascript:void(0)" title="Voice Command" data-action="voiceCommand"><i class="fa fa-microphone"></i></a>
                <div class="popover bottom"><div class="arrow"></div>
                    <div class="popover-content">
                        <h4 class="vc-title">Voice command activated <br><small>Please speak clearly into the mic</small></h4>
                        <h4 class="vc-title-error text-center">
                            <i class="fa fa-microphone-slash"></i> Voice command failed
                            <br><small class="txt-color-red">Must <strong>"Allow"</strong> Microphone</small>
                            <br><small class="txt-color-red">Must have <strong>Internet Connection</strong></small>
                        </h4>
                        <a href="javascript:void(0);" class="btn btn-success" onclick="commands.help()">See Commands</a>
                        <a href="javascript:void(0);" class="btn bg-color-purple txt-color-white" onclick="$('#speech-btn .popover').fadeOut(50);">Close Popup</a>
                    </div>
                </div>
            </div>
        </div>-->
        <!-- end voice command -->

        <!-- multiple lang dropdown : find all flags in the flags page
        <ul class="header-dropdown-list hidden-xs">
            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="/img/blank.gif" class="flag flag-us" alt="United States"> <span> English (US) </span> <i class="fa fa-angle-down"></i> </a>
                <ul class="dropdown-menu pull-right">
                    <li class="active">
                        <a href="javascript:void(0);"><img src="/img/blank.gif" class="flag flag-us" alt="United States"> English (US)</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="/img/blank.gif" class="flag flag-fr" alt="France"> Français</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="/img/blank.gif" class="flag flag-es" alt="Spanish"> Español</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-de" alt="German"> Deutsch</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-jp" alt="Japan"> 日本語</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-cn" alt="China"> 中文</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-it" alt="Italy"> Italiano</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-pt" alt="Portugal"> Portugal</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-ru" alt="Russia"> Русский язык</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><img src="img/blank.gif" class="flag flag-kr" alt="Korea"> 한국어</a>
                    </li>

                </ul>
            </li>
        </ul>-->
        <!-- end multiple lang -->

    </div>
    <!-- end pulled right: nav area -->

</header>

modules/cpanel/views/layouts/left-panel.php
<aside id="left-panel">

    <!-- User info -->
    <div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as it -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
						<img src="/img/avatars/sunny.png" alt="me" class="online">
						<span>
							Admin
						</span>
						<i class="fa fa-angle-down"></i>
					</a>

				</span>
    </div>
    <!-- end user info -->

    <nav>

        <ul style="">
            <li <?php if(Yii::$app->controller->id == "default") echo "class='active'" ?>>
                <?php $views_count = 5; ?>
                <a href="/" title="<?= \Yii::t('app','Dashboard')?>"><i class="fa fa-lg fa-fw fa-desktop"></i> <?php if($views_count) { ?> <span class="badge pull-right inbox-badge margin-right-13 bg-color-teal"><?= $views_count ?></span> <?php } ?> <span class="menu-item-parent"><?= \Yii::t('app','Dashboard')?></span></a>
            </li>
            <li <?php if(Yii::$app->controller->id == "company") echo "class='active'" ?>>
                <a href="<?= \yii\helpers\Url::to(['company/list']) ?>" title="<?= \Yii::t('app','Companies')?>"><i class="fa fa-lg fa-fw fa-university"></i> <span class="menu-item-parent"><?= \Yii::t('app','Companies')?></span></a>
            </li>
            <li <?php if(Yii::$app->controller->id == "agents") echo "class='active'" ?>>
                <a href="<?= \yii\helpers\Url::to(['agent/list']) ?>" title="<?= \Yii::t('app','Agents')?>"><i class="fa fa-lg fa-fw fa-user"></i> <span class="menu-item-parent"><?= \Yii::t('app','Agents')?></span></a>
            </li>
            <li <?php if(Yii::$app->controller->id == "warehouse") echo "class='active'" ?>>
                <a href="<?= \yii\helpers\Url::to(['warehouse/list']) ?>"><i class="fa fa-lg fa-fw fa-cubes"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Warehouses'); ?></span></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-navicon"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Nomenclature'); ?></span></a>
                <ul>
                    <li <?php if(Yii::$app->controller->id == "category-product") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['category-product/list']) ?>"><i class="fa fa-lg fa-fw fa-folder"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Product categories'); ?></span></a>
                    </li>
                    <li <?php if(Yii::$app->controller->id == "product" && (Yii::$app->controller->action->id == "list") ) echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['product/list']) ?>"><i class="fa fa-lg fa-fw fa-shopping-cart"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Products and services'); ?></span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-lg fa-fw fa-check-square-o"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Attributes'); ?></span></a>
                        <ul>
                            <li <?php if(Yii::$app->controller->id == "attribute-group") echo "class='active'" ?>>
                                <a href="<?= \yii\helpers\Url::to(['attribute-group/list']) ?>"> <span class="menu-item-parent"><?= \Yii::t('app', 'Groups'); ?></span></a>
                            </li>
                            <li <?php if(Yii::$app->controller->id == "attribute") echo "class='active'" ?>>
                                <a href="<?= \yii\helpers\Url::to(['attribute/list']) ?>"> <span class="menu-item-parent"><?= \Yii::t('app', 'Attributes'); ?></span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-tags"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Pricing'); ?></span></a>
                <ul>
                    <li <?php if(Yii::$app->controller->id == "pricelist" && (Yii::$app->controller->action->id == "list" || Yii::$app->controller->action->id == "create" || Yii::$app->controller->action->id == "update")) echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['pricelist/list']) ?>" title="<?= \Yii::t('app','Price lists')?>"><i class="fa fa-lg fa-fw fa-tags"></i> <span class="menu-item-parent"><?= \Yii::t('app','Price lists')?></span></a>
                    </li>
                    <li <?php if(Yii::$app->controller->id == "price-type") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['price-type/list']) ?>"><i class="fa fa-lg fa-fw fa-sliders"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Price types'); ?></span></a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-list-alt"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Documents'); ?></span></a>
                <ul>
                    <li <?php if(Yii::$app->controller->id == "doc-receive") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['doc-receive/list']) ?>" title="<?= \Yii::t('app','Doc receive product')?>"><i class="fa fa-lg fa-fw fa-calculator txt-color-orange"></i> <span class="menu-item-parent"><?= \Yii::t('app','Doc receive product')?> (В разработке)</span></a>
                    </li>
                    <li <?php if(Yii::$app->controller->id == "doc-estimate") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['doc-estimate/list']) ?>" title="<?= \Yii::t('app','My estimates')?>"><i class="fa fa-lg fa-fw fa-calculator txt-color-orange"></i> <span class="menu-item-parent"><?= \Yii::t('app','Estimates')?></span></a>
                    </li>
                </ul>
            </li>            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-cogs"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Settings'); ?></span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
                <ul>
                    <li <?php if(Yii::$app->controller->id == "user") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['user/list']) ?>"><i class="fa fa-lg fa-fw fa-users"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Users'); ?></span></a>
                    </li>
                    <li <?php if(Yii::$app->controller->id == "status") echo "class='active'" ?>>
                        <a href="<?= \yii\helpers\Url::to(['status/list']) ?>"><i class="fa fa-lg fa-fw fa-check-circle"></i> <span class="menu-item-parent"><?= \Yii::t('app', 'Statuses'); ?></span></a>
                    </li>

                </ul>
            </li>

        </ul>
    </nav>


			<span class="minifyme" data-action="minifyMenu">
				<i class="fa fa-arrow-circle-left hit"></i>
			</span>

</aside>

modules/cpanel/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\modules\cpanel\assets\CpanelAsset;

CpanelAsset::register($this);
app\extensions\smartadmin\assets\SmartAdminAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
    <?php $this->head() ?>
</head>
<body class="animated fadeInDown">
<?php $this->beginBody() ?>

<?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/cpanel/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\modules\cpanel\assets\CpanelAsset;

CpanelAsset::register($this);
app\extensions\smartadmin\assets\SmartAdminAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
    <?php $this->head() ?>
</head>
<body class="desktop-detected pace-done">
<?php $this->beginBody() ?>

<div class="pace  pace-inactive"><div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(0%, 0px, 0px);">
        <div class="pace-progress-inner"></div>
    </div>
    <div class="pace-activity"></div></div>

<?= $this->render('header'); ?>

<?= $this->render('left-panel'); ?>

<?= $this->render('main-content', ['content' => $content]); ?>

<?= $this->render('footer'); ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>