modules/cpanel/controllers/AttributeController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\Attribute;
use app\modules\cpanel\components\CpanelController;
use yii\web\Response;
use yii\widgets\ActiveForm;

class AttributeController extends CpanelController
{

    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = Attribute::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        if($new === true){
            $model = $this->createModel($this->modelName);
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

             if ($model->save()) {
                $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            return $this->redirect('list');
        }

        if(\Yii::$app->request->isAjax)
            if($model->errors) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $result = array('error' => 'true');
                return array_merge($result, ActiveForm::validate($model));
            } else
                return $this->renderAjax('form', ['model' => $model, 'callback' => \Yii::$app->request->get('callback')]);


    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect(['list']);

    }

    public function actionList(){
        $model = $this->createModel($this->modelName);

        return $this->render('list', ['provider' => $model->getProvider()]);

    }

}

modules/cpanel/controllers/ConfirmController.php
<?php
namespace app\modules\cpanel\controllers;

use app\modules\cpanel\components\CpanelController;
use yii\web\Response;

class ConfirmController extends CpanelController
{

    // action = delete, deleteAll
    public function actionIndex($model, $id, $action)
    {
        $action_url = \yii\helpers\Url::toRoute(["{$model}/{$action}", 'id' => $id]);
        return $this->renderAjax('form', ['id' => $id, 'action_url' => $action_url, 'callback' => \Yii::$app->request->get('callback') ]);
    }

}

modules/cpanel/views/attribute/form.php
<?php

use \yii\widgets\Pjax;

$this->title = \Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Attributes'),
    'url' => \yii\helpers\Url::to(['attribute/list'])];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<section id="widget-grid" class="">
    <?php $form = \yii\bootstrap\ActiveForm::begin([
        'id' =>  'attribute-form' . $model->id,
        'method' => 'post',
        'options' => [
            'class' => 'form-horizontal',
            'enctype'=>'multipart/form-data'],
        'validateOnChange' => true,
        'validateOnBlur' => true,
        'validateOnType'=> true,
    ]); ?>
    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="true" data-widget-editbutton="true">
                <header>
                    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
                    <h2><?= \Yii::t('app', 'Attribute') ?></h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body">


                        <?= $form->field($model, 'name',
                                [   'template' => '{label}<div class="col-md-9">{input}</div>{hint}{error}',
                                    'labelOptions' => ['class' => 'col-md-3 control-label'],
                                ])->textInput();

                        ?>


                        <?= $form->field($model, 'attribute_group_id',
                                [   'template' => '{label}<div class="col-md-6">{input}</div>{hint}{error}',
                                    'labelOptions' => ['class' => 'col-md-3 control-label'],
                                ])->dropDownList( \yii\helpers\ArrayHelper::map( \app\models\AttributeGroup::find()->orderBy('name')->asArray()->all(), 'id', 'name' ) , ['prompt' => \Yii::t('app', 'Choose ...')]);
                        ?>

                        <?= $form->field($model, 'sort',
                                [   'template' => '{label}<div class="col-md-2">{input}</div>{hint}{error}',
                                    'labelOptions' => ['class' => 'col-md-3 control-label'],
                                ])->textInput();
                        ?>


                    </div>
                </div>

            </div>

        </article>
    </div>


    <div class="form-actions">
        <div class="row">
            <div class="col-md-12">
                <?= \yii\bootstrap\Html::button(\Yii::t('app','Save'), ['onclick' => 'submitFormButton('.$callback.')', 'class' => 'showModalButton btn btn-success']); ?>

                <?= \yii\helpers\Html::button('<i class="fa fa-angle-left"></i> '. \Yii::t('app','Back'),
                    [
                        'class' => 'btn btn-success pull-left',
                        'data-dismiss' => "modal" ,
                        'aria-hidden' => "true"
                    ]);
                ?>
            </div>
        </div>
    </div>

    <?php
    $save_url = ($model->isNewRecord ? \yii\helpers\Url::to(['attribute/create']) : \yii\helpers\Url::to(['attribute/update', 'id' => $model->id]));

    $this->registerJs(<<<JS

    function submitFormButton(callback){
        var form = $("#attribute-form$model->id"), 
            data = form.data("yiiActiveForm");
            $.each(data.attributes, function() {
                this.status = 3;
            });
            form.yiiActiveForm("validate");
                 
            if(!form.find(".has-error").length) {
                 
                  $.ajax({
                  url: '$save_url',
                  type: 'post',
                  data: form.serialize(),
                  success: function (response) {
                     console.log(response);                  
                    if(!response.error){
                        form.closest('.modal').modal('hide'); 
                        setTimeout(callback, 200);
                    }

                  }
             });    
             }
             
                    
    }


   


JS
        , \yii\web\View::POS_END);

    ?>

    <?php $form->end();?>
</section>

<?php


?>

modules/cpanel/views/attribute/list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\dynagrid\DynaGrid;
use kartik\grid\GridView;
use app\extensions\smartadmin\widgets\SmartWidgetSection;
use app\extensions\smartadmin\widgets\SmartWidget;
use yii\widgets\Pjax;

$this->title = \Yii::t('app', 'Attributes');
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row-margin row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php echo $button_create = \yii\bootstrap\Modal::widget([
            'id' => 'attr-modal-create',
            'closeButton' => ['tag' => 'button', 'label' => 'close'],
            'toggleButton' => [
                'label' => '<i class="fa fa-plus"></i> ' . \Yii::t('app','Add'),
                'tag' => 'a',
                'data-target' => '#attr-modal-create',
                'href' => \yii\helpers\Url::toRoute(['attribute/create', 'callback' => 'buttonCallback']),
                'class' => 'btn btn-success pull-right',
            ],
            'clientOptions' => false,
        ]); ?>
    </div>
</div>

<?php SmartWidgetSection::begin(); ?>


<?php
$columns = [
    [
        'attribute' => 'name',
        'headerOptions' => ['style'=>'width: 50%'],
    ],
    [
        'attribute' => 'attributeGroup',
        'headerOptions' => ['style'=>'width: 38%'],
        'format' => 'html',
        'value'=>function ($model) {
            return isset($model->attributeGroup) ? $model->attributeGroup->name : '' ;
        },
    ],
    [
        'class'=>'kartik\grid\ActionColumn',
        'dropdown'=>false,
        'headerOptions' => ['style'=>'min-width: 100px'],
        'order'=>DynaGrid::ORDER_FIX_RIGHT,
        'template' => '{update} {delete}',
        'buttons' => [
            'update' => function ($url, $model, $key) {

                $button_update = \yii\bootstrap\Modal::widget([
                    'id' => 'attr-modal-update'.$model->id,
                    'closeButton' => ['tag' => 'button', 'label' => 'close'],
                    'toggleButton' => [
                        'label' => '<i class="fa fa-pencil"></i> ',
                        'tag' => 'a',
                        'data-target' => '#attr-modal-update'.$model->id,
                        'href' => \yii\helpers\Url::toRoute(['attribute/update', 'id' => $model->id, 'callback' => 'buttonCallback']),
                        'class' => 'btn btn-success pull-left',
                    ],
                    'clientOptions' => false,
                ]);
                return $button_update;
                //  return Html::a('<span class="fa fa-pencil"></span>', $url, ['class' => 'btn btn-success']);
            },
            'delete' => function ($url, $model, $key) {
                $button_delete = \yii\bootstrap\Modal::widget([
                    'id' => 'attr-modal-delete' . $model->id,
                    'options' => ['class' => 'bootstrap-dialog type-danger fade'],
                    'closeButton' => ['tag' => 'button', 'label' => 'x'],
                    'toggleButton' => [
                        'label' => '<i class="fa fa-trash"></i> ',
                        'tag' => 'a',
                        'data-target' => '#attr-modal-delete'.$model->id,
                        'href' => \yii\helpers\Url::toRoute(['confirm/index', 'model' => 'attribute', 'id' => $model->id, 'action' => 'delete']),
                        'class' => 'btn btn-danger',
                    ],
                    'clientOptions' => false,
                ]);
                return $button_delete;
            },

        ],
    ],
    [
        'class'=>'kartik\grid\CheckboxColumn',  'order'=>DynaGrid::ORDER_FIX_RIGHT,
    ],
]; ?>


<div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <?php
        SmartWidget::begin(['title' => $this->title, 'icon' => 'fa-table', 'editbutton' => false, 'deletebutton' => false, 'theme' => 'jarviswidget-color-darken']);
        ?>

        <?php Pjax::begin(['id' => 'pjax-attr' ]) ?>

        <?php echo DynaGrid::widget([
            'columns'=>$columns,
            'storage'=>DynaGrid::TYPE_COOKIE,
            'theme'=>'panel-default',
            'gridOptions'=>[
                'dataProvider'=> $provider,
             //   'filterModel'=> $searchModel,
                'panel'=>['heading'=> false, 'before' => false],
            ],
            'options'=>['id'=>'dynagrid-1'] // a unique identifier is important
        ]); ?>

        <?php Pjax::end() ?>
        <?php SmartWidget::end(); ?>



    </article>
</div>
<?php SmartWidgetSection::end(); ?>

<?php

$this->registerJs(<<<JS

    function buttonCallback(form){
        $.pjax.reload({container:"#pjax-attr"});  //Reload GridView    
    }  


JS
    , \yii\web\View::POS_END);

?>