modules/cpanel/controllers/ConfirmController.php
<?php
namespace app\modules\cpanel\controllers;

use app\modules\cpanel\components\CpanelController;
use yii\web\Response;

class ConfirmController extends CpanelController
{

    // action = delete, deleteAll
    public function actionIndex($model, $id, $action)
    {
        $action_url = \yii\helpers\Url::toRoute(["{$model}/{$action}", 'id' => $id]);
        return $this->renderAjax('form', ['id' => $id, 'action_url' => $action_url, 'callback' => \Yii::$app->request->get('callback') ]);
    }

}

modules/cpanel/controllers/ProductController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\CategoryProduct;
use app\models\Product;
use app\models\ProductAttribute;
use app\models\ProductPrice;
use app\models\ProductVariant;
use app\modules\cpanel\components\CpanelController;
use app\modules\cpanel\models\Model;
use yii\data\ActiveDataProvider;

use trntv\filekit\actions\DeleteAction;
use trntv\filekit\actions\UploadAction;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Response;
use yii\widgets\ActiveForm;

class ProductController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function actions()
    {
        return [
            'image-upload' => [
                'class' => UploadAction::className(),
                'deleteRoute' => 'uploads-delete',
                'validationRules' => [
                    ['file', 'image', 'extensions' => 'png, jpg'],
                ]
            ],
            'uploads-delete' => [
                'class' => DeleteAction::className()
            ],
        ];
    }

    public function init()
    {
        $this->modelName = Product::className();
        parent::init();
    }

    public function actionServiceCreate()
    {
        return $this->actionUpdate(true, 'service');
    }

    public function actionProductCreate()
    {
        return $this->actionUpdate(true, 'product');
    }

    public function actionUpdate($new = false, $type = 'product')
    {

        $listCategories = array( 0 => \Yii::t('app', 'Root category'));
        $modelsPrice = [];
        $modelsAttribute = [];
        $modelsVariant = [];

        $cats = CategoryProduct::find()->orderBy('name')->all();

        foreach ($cats as $cat) {
            $listCategories[$cat->id] = $cat->name;
        }

        if($new === true){
            $model = $this->createModel($this->modelName);
          //  $modelsPrice = [new ProductPrice()];
            $modelsAttribute = [new ProductAttribute()];
            $modelsVariant = [new ProductVariant()];

        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
            if($model) {
                switch($model->product_type_id){
                    case Product::TYPE_PRODUCT: $type = 'product'; break;
                    case Product::TYPE_SERVICE: $type = 'service'; break;
                }
            }
           /* foreach ($model->prices as $price){
                $modelsPrice[] = $price;
            }
            if(!$modelsPrice) $modelsPrice = [new ProductPrice()];
*/
            foreach ($model->productAttributes as $attribute){
                $modelsAttribute[] = $attribute;
            }
            if(!$modelsAttribute) $modelsAttribute = [new ProductAttribute()];

            foreach ($model->productVariants as $variant){
                $modelsVariant[] = $variant;
            }
            if(!$modelsVariant) $modelsVariant = [new ProductVariant()];
        }


        if ($model->load(\Yii::$app->request->post()) ) {
          //  $modelsPrice = Model::createMultiple(ProductPrice::classname());
            $modelsAttribute = Model::createMultiple(ProductAttribute::classname());
            $modelsVariant = Model::createMultiple(ProductVariant::classname());

        //    Model::loadMultiple($modelsPrice, \Yii::$app->request->post());
            Model::loadMultiple($modelsAttribute, \Yii::$app->request->post());
            Model::loadMultiple($modelsVariant, \Yii::$app->request->post());

            if ( $model->validate()
                && Model::validateMultiple($modelsPrice)
                && Model::validateMultiple($modelsAttribute)
                && Model::validateMultiple($modelsVariant)) {

                if ($model->save()) {
                    //$model->deletePrices();
                    $model->deleteAttributes();
                    $model->deleteVariants();
                   /* foreach ($modelsPrice as $item) {
                        $item->link('product', $model);
                        $item->save(false);
                    } */
                    foreach ($modelsAttribute as $item) {
                        $item->link('product', $model);
                        $item->save(false);
                    }
                   // \Yii::info(ArrayHelper::toArray($modelsVariant), 'test');
                    foreach ($modelsVariant as $item) {
                        $item->link('product', $model);
                        $item->save(true);
                    }
                    $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
                } else {
                    $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
                }
            }

            return $this->redirect('list');
        }

        if(\Yii::$app->request->isAjax)
            if($model->errors) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $result = array('error' => 'true');
                return array_merge($result, ActiveForm::validate($model));
            } else
                return $this->renderAjax(($type == 'product' ? 'product-form' : 'service-form'),
                    [
                        'model' => $model,
                        'listCategories' => $listCategories,
                        'modelsPrice' => $modelsPrice,
                        'modelsAttribute' => $modelsAttribute,
                        'modelsVariant' => $modelsVariant,
                        'callback' => \Yii::$app->request->get('callback')
                    ]);



      //  return $this->render(($type == 'product' ? 'product-form' : 'service-form'), ['model' => $model, 'listCategories' => $listCategories,
      //      'modelsPrice' => $modelsPrice]);

    }

    public function actionGetCurrentPrice(){
        if(!\Yii::$app->request->isAjax)
            return 'Ajax request is not found!';

        if(\Yii::$app->request->post() && isset(\Yii::$app->request->post()['product']) ){
            $post = \Yii::$app->request->post()['product'];
            $product = Product::findOne($post['product_id']);
            if($product) {
                $response = [];
                $response['name'] = $product->name;
                $response['product_id'] = $product->id;
                $response['quantity'] = $post['quantity'];
                $response['period'] = $post['period'];
                $response['price'] = $product->getCurrentPrice(null, $post['period']);
                $response['total_sum'] = $response['quantity'] * $response['price'];

                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return $response;
            }
        }
        return 'Empty';
    }

    public function actionTree()
    {
      //  echo "asdasd"; exit;
       // if(!\Yii::$app->request->isAjax)
       //    return 'Ajax request is not found!';
       // else {
          \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return CategoryProduct::find()->asArray()->all();
       // }
    }

    public function actionDelete($id)
    {
        $type = 'product';
        $model = $this->findModel($this->modelName, $id);
        if($model) {
            switch($model->product_type_id){
                case Product::TYPE_PRODUCT: $type = 'product'; break;
                case Product::TYPE_SERVICE: $type = 'service'; break;
            }
        }        
        if($model->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect([($type == 'product' ? 'list' : 'list')]);

    }

    public function actionGenerateCode()
    {
        return $this->render('form', ['model' => $this->createModel($this->modelName),
                                      'barcode' => Product::generateBarcode(),
                                      'listCategories' => array() ]);
    }

    public function actionList(){

        $category_id = \Yii::$app->request->get('category_id');

        $dataProvider = new ActiveDataProvider([
            'query' => Product::find()->productService($category_id),
            'sort' => [
            ],
        ]);

        $categories = CategoryProduct::find()->all();

        return $this->render('list', ['provider' => $dataProvider, 'categories' => $categories]);

    }


}

modules/cpanel/views/product/list.php
<?php
use app\extensions\smartadmin\widgets\SmartGrid;
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\dynagrid\DynaGrid;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use app\components\widgets\Modal;
use app\extensions\smartadmin\widgets\SmartWidgetSection;
use app\extensions\smartadmin\widgets\SmartWidget;

$this->title = \Yii::t('app', 'Product');
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>


    <div class="row-margin row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <?= Modal::widget([
                'id' => 'service-modal-create',
                'closeButton' => ['tag' => 'button', 'label' => 'close'],
                'toggleButton' => [
                    'label' => '<i class="fa fa-plus"></i> ' .\Yii::t('app','Add service'),
                    'tag' => 'a',
                    'data-target' => '#service-modal-create',
                    'href' => \yii\helpers\Url::toRoute(['product/service-create', 'callback' => 'buttonCallback']),
                    'class' => 'btn btn-success pull-right',
                ],
                'clientOptions' => false,
            ]); ?>

            <?= Modal::widget([
                'id' => 'product-modal-create',
                'closeButton' => ['tag' => 'button', 'label' => 'close'],
                'options' => ['tabindex' => false],
                'size' => Modal::SIZE_LARGE,
                'toggleButton' => [
                    'label' => '<i class="fa fa-plus"></i> ' . \Yii::t('app','Add product'),
                    'tag' => 'a',
                    'data-target' => '#product-modal-create',
                    'href' => \yii\helpers\Url::toRoute(['product/product-create', 'callback' => 'buttonCallback']),
                    'class' => 'btn btn-success pull-right',
                    'style' => 'margin-right: 10px'
                ],
                'clientOptions' => false,
            ]); ?>

        </div>
    </div>

<?php SmartWidgetSection::begin(); ?>
    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <?php
            $columns = [
                [
                    'attribute' => 'name',
                    'headerOptions' => ['style'=>'width: 55%'],
                ],
                [
                    'attribute' => 'categoryName',
                    'headerOptions' => ['style'=>'width: 30%'],
                ],
                [
                    'attribute' => 'product_type_id',
                    'headerOptions' => ['style'=>'width: 10%'],
                    'format' => 'html',
                    'value'=>function ($model) {
                        switch($model->product_type_id){
                            case \app\models\Product::TYPE_PRODUCT: return \Yii::t('app', 'Product');
                            case \app\models\Product::TYPE_SERVICE: return \Yii::t('app', 'Service');
                            default: return '';
                        }

                    },
                ],
                [
                    'class'=>'kartik\grid\ActionColumn',
                    'dropdown'=>false,
                    'headerOptions' => ['style'=>'min-width: 100px'],
                    'order'=>DynaGrid::ORDER_FIX_RIGHT,
                    'template' => '{update} {delete}',
                    'buttons' => [
                        'update' => function ($url, $model, $key) {

                            $button_update = Modal::widget([
                                'id' => 'product-modal-update'.$model->id,
                                'closeButton' => ['tag' => 'button', 'label' => 'close'],
                                'options' => ['tabindex' => false],
                                'size' => ($model->product_type_id == \app\models\Product::TYPE_PRODUCT ? Modal::SIZE_LARGE : Modal::SIZE_DEFAULT),
                                'toggleButton' => [
                                    'label' => '<i class="fa fa-pencil"></i> ',
                                    'tag' => 'a',
                                    'data-target' => '#product-modal-update'.$model->id,
                                    'href' => \yii\helpers\Url::toRoute(['product/update', 'id' => $model->id, 'callback' => 'buttonCallback']),
                                    'class' => 'btn btn-success pull-left',
                                ],
                                'clientOptions' => false,
                            ]);
                            return $button_update;
                        },
                        'delete' => function ($url, $model, $key) {
                            $button_delete = Modal::widget([
                                'id' => 'product-modal-delete' . $model->id,
                                'options' => ['class' => 'bootstrap-dialog type-danger fade'],
                                'closeButton' => ['tag' => 'button', 'label' => 'x'],
                                'toggleButton' => [
                                    'label' => '<i class="fa fa-trash"></i> ',
                                    'tag' => 'a',
                                    'data-target' => '#product-modal-delete'.$model->id,
                                    'href' => \yii\helpers\Url::toRoute(['confirm/index', 'model' => 'product', 'id' => $model->id, 'action' => 'delete']),
                                    'class' => 'btn btn-danger',
                                ],
                                'clientOptions' => false,
                            ]);
                            return $button_delete;
                        },

                    ],
                ],
                [
                    'class'=>'kartik\grid\CheckboxColumn',  'order'=>DynaGrid::ORDER_FIX_RIGHT,
                ],
            ]; ?>

            <?php

            $onSelect = new \yii\web\JsExpression(<<<JS
    function (undefined, item) {
    console.log(item);
    $.pjax.reload({
        container:"#pjax-products",
        type: 'GET',
        url: item.href
    });
}
JS
            );
            $tree = \app\components\widgets\TreeView::widget([
                'data' => \app\models\CategoryProduct::getChidsArray(),
                'size' => \execut\widget\TreeView::SIZE_MIDDLE,
                'search' => false,
                'header' => \Yii::t('app','Categories'),
                'searchOptions' => [
                  //  'inputOptions' => [
                  //      'placeholder' => 'Search category...'
                  //  ],
                ],
                'clientOptions' => [
                    'onNodeSelected' => $onSelect,
                   // 'selectedBackColor' => 'rgb(40, 153, 57)',
                    'borderColor' => '#ddd',
                    'enableLinks' => false
                ],
            ]);



            SmartWidget::begin(['title' => $this->title, 'icon' => 'fa-table', 'editbutton' => false, 'deletebutton' => false, 'theme' => 'jarviswidget-color-darken']);
            ?>


           <div class="col-sm-4 col-md-4 col-lg-3">
                <?= $tree ?>
                <div class="row-margin row">
                    <a href="<?= Url::to(['product/list'])?>" class="btn btn-primary pull-left"?><?= \Yii::t('app', 'Show all') ?></a>
                </div>
            </div>

            <div class="col-sm-8 col-md-8 col-lg-9">

            <?php Pjax::begin(['id' => 'pjax-products']) ?>
            <?= DynaGrid::widget([
                'columns'=>$columns,
                'storage'=>DynaGrid::TYPE_COOKIE,
                'theme'=>'panel-default',
                'gridOptions'=>[
                    'dataProvider'=>$provider,
                    //   'filterModel'=>$searchModel,
                    'panel'=>['heading'=> false, 'before' => false],
                ],
                'options'=>['id'=>'dynagrid-1'] // a unique identifier is important
            ]); ?>
            <?php Pjax::end(); ?>
            </div>

            <?php SmartWidget::end(); ?>



        </article>
    </div>
<?php SmartWidgetSection::end(); ?>


<?php

$this->registerJs(<<<JS

    function buttonCallback(form){
        $.pjax.reload({container:"#pjax-products"});  //Reload GridView    
    }  


JS
    , \yii\web\View::POS_END);

?>

modules/cpanel/views/product/product-form.php
<?php

use \yii\widgets\Pjax;
use wbraganca\dynamicform\DynamicFormWidget;

$this->title = \Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Products and services'),
    'url' => \yii\helpers\Url::to(['product/list'])];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<section id="widget-grid" class="">
    <?php $form = \yii\widgets\ActiveForm::begin([
        'id' =>  'product-form' . $model->id,
        'method' => 'post',
        'options' => [
            'class' => 'form-horizontal',
            'enctype'=>'multipart/form-data'],
        'validateOnChange' => true,
        'validateOnBlur' => true,
        'validateOnType'=> true,
    ]); ?>
    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="true" data-widget-editbutton="true">
                <header>
                    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
                    <h2><?= \Yii::t('app', 'Product') ?></h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body">


                        <?= $form->field($model, 'name',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->textInput();
                        ?>

                        <?= $form->field($model, 'category_id',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->dropDownList($listCategories);
                        ?>

                        <?= $form->field($model, 'model',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->textInput();
                        ?>

                        <?= $form->field($model, 'barcode',
                            [   'template' => '{label}<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">{input}</div><div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-xs-2 col-sm-2 col-md-2 col-lg-2 control-label'],
                            ])->textInput(['value' => isset($barcode) ? $barcode : $model->barcode]);
                        ?>

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <?= $form->field($model, 'image',
                                    [   'template' => '{label}<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">{input}</div><div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>{hint}{error}',
                                        'labelOptions' => ['class' => 'col-xs-2 col-sm-2 col-md-2 col-lg-2 control-label']]
                                )->label(Yii::t('app', 'Image'))->widget(
                                    \trntv\filekit\widget\Upload::className(),
                                    [
                                        'id' => 'wid-up'.$model->id,
                                        'url' => ['image-upload'],
                                    ]);
                                ?>
                            </div>
                        </div>


                        <?= $form->field($model, 'product_type_id')->hiddenInput(['value' => \app\models\Product::TYPE_PRODUCT])->label(false);
                        ?>

                        <?= \yii\bootstrap\Tabs::widget([
                            'options' => ['id' => 'tab-widget' . $model->id, 'style' => 'margin-bottom: 15px'],
                            'items' => [
                                [
                                    'label' => \Yii::t('app', 'Attributes'),
                                    'content' => $this->render('product-form-tab-attribute', ['form' => $form, 'model' => $model, 'modelsAttribute' => $modelsAttribute]),
                                    'active' => true
                                ],
                                [
                                    'label' => \Yii::t('app', 'Variants'),
                                    'content' => $this->render('product-form-tab-variant', ['form' => $form, 'model' => $model, 'modelsVariant' => $modelsVariant]),
                                    //  'active' => true,
                                    //'headerOptions' => [],
                                ],
                                [
                                    'label' => \Yii::t('app', 'Prices'),
                                    'content' => '',
                                    //   'active' => true,
                                    //'headerOptions' => [],
                                ],

                            ],
                        ]); ?>

                    </div>
                </div>

            </div>

        </article>
    </div>


    <div class="form-actions">
        <div class="row">
            <div class="col-md-12">
                <?= \yii\bootstrap\Html::button(\Yii::t('app','Save'), ['onclick' => 'submitFormButton('.$callback.')', 'class' => 'showModalButton btn btn-success']); ?>

                <?= \yii\helpers\Html::button('<i class="fa fa-angle-left"></i> '. \Yii::t('app','Back'),
                    [
                        'class' => 'btn btn-success pull-left',
                        'data-dismiss' => "modal" ,
                        'aria-hidden' => "true"
                    ]);
                ?>
            </div>
        </div>
    </div>

    <?php
    $save_url = ($model->isNewRecord ? \yii\helpers\Url::to(['product/product-create']) : \yii\helpers\Url::to(['product/update', 'id' => $model->id]));

    $this->registerJs(<<<JS

    function submitFormButton(callback){
        var form = $("#product-form$model->id"), 
            data = form.data("yiiActiveForm");
            $.each(data.attributes, function() {
                this.status = 3;
            });
            form.yiiActiveForm("validate");
                 
            if(!form.find(".has-error").length) {
                 
                  $.ajax({
                  url: '$save_url',
                  type: 'post',
                  data: form.serialize(),
                  success: function (response) {
                     console.log(response);                  
                    if(!response.error){
                        form.closest('.modal').modal('hide'); 
                        setTimeout(callback, 200);
                    }

                  }
             });    
             }
             
                    
    }


   


JS
        , \yii\web\View::POS_END);

    ?>

    <?php $form->end();?>
</section>

modules/cpanel/views/product/service-form.php
<?php

use \yii\widgets\Pjax;

$this->title = \Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Services'),
    'url' => \yii\helpers\Url::to(['product/list'])];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<section id="widget-grid" class="">
    <?php $form = \yii\bootstrap\ActiveForm::begin([
        'id' =>  'service-form' . $model->id,
        'method' => 'post',
        'options' => [
            'class' => 'form-horizontal',
            'enctype'=>'multipart/form-data'],
        'validateOnChange' => true,
        'validateOnBlur' => true,
        'validateOnType'=> true,
    ]); ?>
    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="true" data-widget-editbutton="true">
                <header>
                    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
                    <h2><?= \Yii::t('app', 'Service') ?></h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body">


                        <?= $form->field($model, 'name',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->textInput();
                        ?>

                        <?= $form->field($model, 'category_id',
                            [   'template' => '{label}<div class="col-md-6">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->label(Yii::t('app', 'Category'))->dropDownList( \yii\helpers\ArrayHelper::map( \app\models\CategoryProduct::find()->orderBy('name')->all(), 'id' , 'name'), ['prompt' => \Yii::t('app', 'Choose...')] );
                        ?>

                        <div class="row">
                            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                            </div>
                            <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                                <?= $form->field($model, 'owner_type',
                                    [   'template' => '{label}<div class="col-md-2">{input}</div>{hint}{error}',
                                        'options' => ['style' => 'text-align: left'],
                                        'labelOptions' => ['class' => 'col-md-2 control-label'],
                                    ])->checkbox();
                                ?>
                            </div>
                        </div>

                        <?= $form->field($model, 'product_type_id')->hiddenInput(['value' => \app\models\Product::TYPE_SERVICE])->label(false);
                        ?>



                    </div>
                </div>

            </div>

        </article>
    </div>


    <div class="form-actions">
        <div class="row">
            <div class="col-md-12">
                <?= \yii\bootstrap\Html::button(\Yii::t('app','Save'), ['onclick' => 'submitFormButton('.$callback.')', 'class' => 'showModalButton btn btn-success']); ?>

                <?= \yii\helpers\Html::button('<i class="fa fa-angle-left"></i> '. \Yii::t('app','Back'),
                    [
                        'class' => 'btn btn-success pull-left',
                        'data-dismiss' => "modal" ,
                        'aria-hidden' => "true"
                    ]);
                ?>
            </div>
        </div>
    </div>

    <?php
    $save_url = ($model->isNewRecord ? \yii\helpers\Url::to(['product/service-create']) : \yii\helpers\Url::to(['product/update', 'id' => $model->id]));

    $this->registerJs(<<<JS

    function submitFormButton(callback){
        var form = $("#service-form$model->id"), 
            data = form.data("yiiActiveForm");
            $.each(data.attributes, function() {
                this.status = 3;
            });
            form.yiiActiveForm("validate");
                 
            if(!form.find(".has-error").length) {
                 
                  $.ajax({
                  url: '$save_url',
                  type: 'post',
                  data: form.serialize(),
                  success: function (response) {
                     console.log(response);                  
                    if(!response.error){
                        form.closest('.modal').modal('hide'); 
                        if(callback)
                            setTimeout(callback, 200);
                    }

                  }
             });    
             }
             
                    
    }


   


JS
        , \yii\web\View::POS_END);

    ?>

    <?php $form->end();?>
</section>

<?php


?>