modules/cpanel/controllers/CategoryProductController.php
<?php
namespace app\modules\cpanel\controllers;

use app\models\CategoryProduct;
use app\modules\cpanel\components\CpanelController;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\web\Response;
use yii\widgets\ActiveForm;

class CategoryProductController extends CpanelController
{
    public $defaultAction = 'list';
    private $modelName = '';

    public function init()
    {
        $this->modelName = CategoryProduct::className();
        parent::init();
    }

    public function actionCreate()
    {
        return $this->actionUpdate(true);
    }

    public function actionUpdate($new = false)
    {

        $listCategories = array( 0 => \Yii::t('app', 'Root category'));

        $cats = CategoryProduct::find()->orderBy('name')->all();

        foreach ($cats as $cat) {
            $listCategories[$cat->id] = $cat->name;
        }

        if($new === true){
            $model = $this->createModel($this->modelName);
        }else{
            $model = $this->findModel($this->modelName, \Yii::$app->request->get('id'));
            $listCategories = array_diff($listCategories, array( $model->id => $model->name));
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

             if ($model->save()) {
                $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
            } else {
                $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));
            }
            return $this->redirect('list');
        }

        if(\Yii::$app->request->isAjax)
            if($model->errors) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $result = array('error' => 'true');
                return array_merge($result, ActiveForm::validate($model));
            } else
                return $this->renderAjax('form', ['model' => $model, 'listCategories' => $listCategories, 'callback' => \Yii::$app->request->get('callback')]);

    }

    public function actionDelete($id)
    {
        if($this->findModel($this->modelName, $id)->delete() !== false)
            $this->setFlash('success', \Yii::t('app', 'Modifications have been saved'));
        else
            $this->setFlash('error', \Yii::t('app', 'Modifications have not been saved'));

        return $this->redirect(['list']);

    }

    public function actionList(){

        $dataProvider = new ArrayDataProvider([
            'allModels' => CategoryProduct::find()->all(),
            'sort' => [
                'attributes' => ['fullName'],
                'defaultOrder' => ['fullName' => SORT_ASC]
            ],
        ]);

        return $this->render('list', ['provider' => $dataProvider]);

    }

}

modules/cpanel/controllers/ConfirmController.php
<?php
namespace app\modules\cpanel\controllers;

use app\modules\cpanel\components\CpanelController;
use yii\web\Response;

class ConfirmController extends CpanelController
{

    // action = delete, deleteAll
    public function actionIndex($model, $id, $action)
    {
        $action_url = \yii\helpers\Url::toRoute(["{$model}/{$action}", 'id' => $id]);
        return $this->renderAjax('form', ['id' => $id, 'action_url' => $action_url, 'callback' => \Yii::$app->request->get('callback') ]);
    }

}

modules/cpanel/views/category-product/form.php
<?php

$this->title = \Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Product categories'),
    'url' => \yii\helpers\Url::to(['category-product/list'])];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<section id="widget-grid" class="">
    <?php $form = \yii\bootstrap\ActiveForm::begin([
        'id' => 'form-1',
        'method' => 'post',
        'options' => [
            'class' => 'form-horizontal',
            'enctype'=>'multipart/form-data'],
        'validateOnChange' => true,
        'validateOnBlur' => true,
        'validateOnType'=> true,
    ]); ?>
    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="true" data-widget-editbutton="true">
                <header>
                    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
                    <h2><?= \Yii::t('app', 'Product category') ?></h2>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body">


                        <?= $form->field($model, 'name',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->textInput();
                        ?>

                        <?= $form->field($model, 'parent_id',
                            [   'template' => '{label}<div class="col-md-10">{input}</div>{hint}{error}',
                                'labelOptions' => ['class' => 'col-md-2 control-label'],
                            ])->dropDownList($listCategories);
                        ?>

                    </div>
                </div>

            </div>

        </article>
    </div>

    <div class="form-actions">
        <div class="row">
            <div class="col-md-12">
                <?= \yii\helpers\Html::submitButton('<i class="fa fa-save"></i> '. \Yii::t('app','Save'),
                    ['class' => 'btn btn-primary']
                ); ?>

                <?= \yii\helpers\Html::a('<i class="fa fa-angle-left"></i> '. \Yii::t('app','Back'), \yii\helpers\Url::to(['category-product/list']) , ['class' => 'btn btn-success pull-left']); ?>
            </div>
        </div>
    </div>

    <?php $form->end();?>
</section>

<?php


?>

modules/cpanel/views/category-product/list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\dynagrid\DynaGrid;
use kartik\grid\GridView;
use app\extensions\smartadmin\widgets\SmartWidgetSection;
use app\extensions\smartadmin\widgets\SmartWidget;
use yii\widgets\Pjax;

$this->title = \Yii::t('app', 'Product categories');
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row-margin row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php echo $button_create = \yii\bootstrap\Modal::widget([
            'id' => 'category-product-modal-create',
            'closeButton' => ['tag' => 'button', 'label' => 'close'],
            'toggleButton' => [
                'label' => '<i class="fa fa-plus"></i> ' . \Yii::t('app','Add'),
                'tag' => 'a',
                'data-target' => '#category-product-modal-create',
                'href' => \yii\helpers\Url::toRoute(['category-product/create', 'callback' => 'buttonCallback']),
                'class' => 'btn btn-success pull-right',
            ],
            'clientOptions' => false,
        ]); ?>
    </div>
</div>

<?php SmartWidgetSection::begin(); ?>


<?php
$columns = [
    [
        'attribute' => 'fullName',
        'headerOptions' => ['style'=>'width: 90%'],
    ],
    [
        'class'=>'kartik\grid\ActionColumn',
        'dropdown'=>false,
        'headerOptions' => ['style'=>'min-width: 100px'],
        'order'=>DynaGrid::ORDER_FIX_RIGHT,
        'template' => '{update} {delete}',
        'buttons' => [
            'update' => function ($url, $model, $key) {
                if(!$model->fixed) {
                    $button_update = \yii\bootstrap\Modal::widget([
                        'id' => 'category-product-modal-update' . $model->id,
                        'closeButton' => ['tag' => 'button', 'label' => 'close'],
                        'toggleButton' => [
                            'label' => '<i class="fa fa-pencil"></i> ',
                            'tag' => 'a',
                            'data-target' => '#category-product-modal-update' . $model->id,
                            'href' => \yii\helpers\Url::toRoute(['category-product/update', 'id' => $model->id, 'callback' => 'buttonCallback']),
                            'class' => 'btn btn-success pull-left',
                        ],
                        'clientOptions' => false,
                    ]);
                    return $button_update;
                }
                return '';
                //  return Html::a('<span class="fa fa-pencil"></span>', $url, ['class' => 'btn btn-success']);
            },
            'delete' => function ($url, $model, $key) {
                if(!$model->fixed) {
                    $button_delete = \yii\bootstrap\Modal::widget([
                        'id' => 'category-product-modal-delete' . $model->id,
                        'options' => ['class' => 'bootstrap-dialog type-danger fade'],
                        'closeButton' => ['tag' => 'button', 'label' => 'x'],
                        'toggleButton' => [
                            'label' => '<i class="fa fa-trash"></i> ',
                            'tag' => 'a',
                            'data-target' => '#category-product-modal-delete' . $model->id,
                            'href' => \yii\helpers\Url::toRoute(['confirm/index', 'model' => 'category-product', 'id' => $model->id, 'action' => 'delete']),
                            'class' => 'btn btn-danger',
                        ],
                        'clientOptions' => false,
                    ]);
                    return $button_delete;
                }
                return '';
                //return Html::a('<span class="fa fa-trash"></span>', $url, ['class' => 'btn btn-danger']);
            },

        ],
    ],
    [
        'class'=>'kartik\grid\CheckboxColumn',  'order'=>DynaGrid::ORDER_FIX_RIGHT,
    ],
]; ?>


<div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <?php
        SmartWidget::begin(['title' => $this->title, 'icon' => 'fa-table', 'editbutton' => false, 'deletebutton' => false, 'theme' => 'jarviswidget-color-darken']);
        ?>

        <?php Pjax::begin(['id' => 'pjax-category-product' ]) ?>

        <?php echo DynaGrid::widget([
            'columns'=>$columns,
            'storage'=>DynaGrid::TYPE_COOKIE,
            'theme'=>'panel-default',
            'gridOptions'=>[
                'dataProvider'=> $provider,
                'panel'=>['heading'=> false, 'before' => false],
            ],
            'options'=>['id'=>'dynagrid-1'] // a unique identifier is important
        ]); ?>

        <?php Pjax::end() ?>
        <?php SmartWidget::end(); ?>



    </article>
</div>
<?php SmartWidgetSection::end(); ?>

<?php
$agent_save_url = \yii\helpers\Url::to(['category-product/create']);

$this->registerJs(<<<JS

    function buttonCallback(){
        $.pjax.reload({container:"#pjax-category-product"});  //Reload GridView    
    }  



JS
    , \yii\web\View::POS_END);

?>